server:
  port: 8080
  servlet:
    context-path: /lvs-api
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_vision
      username: root
      password: root
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-user: 20
  data:
    mongodb:
      uri: mongodb://localhost:27017/lung_mongo
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  type-aliases-package: com.rabbit.entity
  mapper-locations: classpath*:mapper/**/*Mapper.xml
